language: python
sudo: false
python: 
  - "3.4"

install:
  - pip install -r requirements.txt
#   - pip install parser

script: python3.4 src/main.py

notifications:
  email: false

branches:
  only:
    - master